Blog App: Integration Specs
rmiyoyo/blog-app pull request #11
Opened 2024-01-17 12:31 UTC by rmiyoyo

# Work Done

#### n+1
- The N+1 problem is solved when fetching all posts and their comments for a user.
![ca1](https://github.com/rmiyoyo/blog-app/assets/120647236/ffd980c3-0e34-4486-8698-810ad6e225c7)
![dfe](https://github.com/rmiyoyo/blog-app/assets/120647236/52ca73a9-407e-4a90-b2b3-7a329dfc1a0d)

#### Integration specs
- Used Capybara to write integration tests for each view in the project.
- User index page:
  - I can see the username of all other users.
  - I can see the profile picture for each user.
  - I can see the number of posts each user has written.
  - When I click on a user, I am redirected to that user's show page.

- user show page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view all of a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.

- User post index page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.

- Post show page:
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each commentor.
  - I can see the comment each commentor left.

2024-01-17 12:57 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @rmiyoyo, and Team👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Good job fixing n+1 problem. ✔️ 
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-17 12:57 UTC, thecodechaser commented on spec/views/user_post_show_spec.rb
>      @user1 = User.create(name: 'John Doe', photo: 'https://placehold.co/200x200',
- [ ] You missed adding the below test for the user show page, Please make sure to add that as requested in the project requirements.
  - Tests that assert you can see the user's first 3 posts.

2024-01-17 12:57 UTC, thecodechaser commented on spec/views/user_post_show_spec.rb
>      @user1 = User.create(name: 'John Doe', photo: 'https://placehold.co/200x200',
- [ ] You missed adding the below tests for the post show page, Please make sure to add them as requested in the project requirements.
  - Tests that assert you can see who wrote the post.
  - Tests that assert you can see the username of each commenter.
  - Tests that assert you can see the comment each commentor left.

2024-01-17 12:57 UTC, thecodechaser commented on spec/views/user_post_show_spec.rb
>      @user1 = User.create(name: 'John Doe', photo: 'https://placehold.co/200x200',
- [ ] All of the tests are failing, Please make sure that all tests pass without any errors.

![image](https://github.com/rmiyoyo/blog-app/assets/83803414/44b92012-4e00-4cd2-9deb-1eade8d3cce1)

2024-01-18 16:27 UTC, rmiyoyo commented
# Work Done After Review
- All tests work
- All instances tested

2024-01-18 18:14 UTC, Ibizugbe requested changes
Hi @Team👋🏼👋🏼👋🏼, 

![request change](https://github.com/rmiyoyo/blog-app/assets/64643995/79e5d46f-4d40-4f5f-b6e2-1e446c9f0b8c)


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅✅✅

- [x] Tests that assert you can see the author of the post, username of each commenter and their comments have been added👍🏼.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-18 18:14 UTC, Ibizugbe commented on spec/views/users_show_spec.rb
> +  end
Just [as suggested by the previous reviewer](https://github.com/rmiyoyo/blog-app/pull/11#discussion_r1455461342)😉, Kindly add a test that asserts that you can see the user's first 3 posts in the `user_show` page as this is a requirement for this milestone😉.

2024-01-18 18:14 UTC, Ibizugbe commented on spec/views/user_post_show_spec.rb
> +  end
[OPTIONAL] Nice job implementing the suggestions from the previous reviewer👍🏼, but I think we can break this `it` block to several `it` blocks to make your tests more descriptive and easier to understand😉.

2024-01-19 09:32 UTC, rmiyoyo commented
# Work Done
I added the following tests:
1. Tests that assert you can see the user's first 3 posts.
2. Tests that assert you can see who wrote the post.
3. Tests that assert you can see the username of each commenter.
4. Tests that assert you can see the comment each commentor left.

2024-01-19 11:13 UTC, fobadara approved these changes
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![APPRVED](https://user-images.githubusercontent.com/62938735/260206857-3c93f52c-5b21-4f6f-8bc4-be158a13d3cd.gif)
## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-19 11:40 UTC, merged